export default {
  //ONBOARD
  start: 'Get started',
  onboardTitle: 'what is this?',
  onboardContent:
    'Our application was created to help you properly monitor and distribute your finances. You no longer need to turn on your computer every time to add data to the table, now you can automate this process!',
  //AUTH
  login: 'login',
  registration: 'registration',
  signIn: 'sign in',
  signUp: 'sign up',
  loginHelp: 'login with',
  forgotPass: 'forgot password?',
  email: 'email',
  username: 'username',
  password: 'password',
  emailUse: 'That email address is already in use!',
  invalidEmail: 'That email address is invalid!',
  emptyFields: "fields can't be empty",
  passValidation: 'password is at least 6 characters',
  wrongPass: 'wrong-password',
  //HOME
  home: 'HOME',
  wallet: 'WALLET',
  operations: 'OPERATIONS',
  settings: 'SETTINGS',
  expenses: 'EXPENSES',
  allExpense: 'all expenses',
  //ADD MODAL
  addCategory: 'create new category ',
  icons: 'icons',
  color: 'color',
  inputName: 'category name',
  close: 'close',
  create: 'create',
  emptyField: 'enter name category',
  isHave: 'this category already exists',
  //REMOVEMODAL
  removeCategory: 'delete category?',
  categoryInfo: 'all information will be deleted!',
  cancelBtn: 'cancel',
  okBtn: 'delete',
  //ADDMONEYMODAL
  addMoney: 'add money',
  removeMoney: 'remove money',
  confirm: 'confirm',
  amount: 'enter the amount',
  description: 'description (optional)',
  //month
  all: 'All',
  1: 'Jan',
  2: 'Feb',
  3: 'Mar',
  4: 'Apr',
  5: 'May',
  6: 'Jun',
  7: 'Jul',
  8: 'Aug',
  9: 'Sep',
  10: 'Oct',
  11: 'Dec',
  12: 'Nov',
  //wallet
  balance: 'Current Balance',
  increase: 'increase',
  decrease: 'decrease',
  goal: 'add goal',
  period: 'period',
  daily: 'daily budget',
  weakly: 'weakly budget',
  month: 'month budget',
  year: 'year budget',
  maxSum: 'max 10 numbers',
  changeSum: 'change the amount',
  //History
  allCat: 'All categories',
  allTrans: 'all transactions',
  wholeAmount: 'the sum of all purchases',
  clear1: 'There have been no operations yet',
  clear2: 'create a category',
  //SETTINGS
  theme: 'Dark mode',
  secure: 'Secure',
  lang: 'Languages',
  cur: 'Currency',
  export: 'Export to excel',
  export1: 'export',
  logOut: 'Log out',
  logOut1: 'exit',
  progress: 'Sorry, this feature is still under development.',
};
