declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '@types/react-redux'
declare module 'i18n-js'
declare module 'styled-components/native'
declare module '@react-native-google-signin/google-signin'
declare module 'react-native-fbsdk'